### PR TITLE
Use proxy instead of MutationObserver for track changes fixes #1

### LINKED ISSUE #1: Album & Artist don't match track
I've noticed while using YT music in GPMDP that the now playing notification and the title bar are showing the artist for the last track I played while showing the correct title.

It looks like YouTube Music sets the title in the playback controls and then sets the album and artist a few milliseconds later. This throws off ytmusic.js as it listens for the title to change and then sends the change:track event. There's a few milliseconds where the title from the new track will be displayed before the album and artist are.

As a temporary fix I've experimented in jccit/ytmusic.js@0e747dd1d0f181f7116a369c1626d3aafa428927 by adding a setTimeout of about 500ms after the change is detected before getting the track details. This does fix the issue but isn't ideal.

### PR DESCRIPTION
**Pull request by jostrander**

### CODE REVIEW

**Comment by gregflynn** [comment]
@jostrander / @MarshallOfSound can we add the bump to `6.1.12` in this PR and :shipit: ?

**Comment by SlackingVeteran** [comment]
@jostrander ytmusic-player-bar no longer has duration. maybe it had when you made these changes but its gone now. 
image

I guess, you could simply revert change made in getCurrentTime to fix it.

**Comment by jostrander** [comment]
If I recall correctly it's not visible in the DOM, but it's a data point on the polymer component that I'm reading.

**Comment by SlackingVeteran** [comment]
I did try your changes before trying to find out why it wasn't title
duration was not being received.

**Comment by jostrander** [comment]
Updated to fetch total duration from another property in that object. Feel free to test accuracy.

**Comment by SlackingVeteran** [comment]
@jostrander that fixed the total duration issue. But I found one issue. When you play a video instead of a song, PlaybackAPI is not able to set title artist and album. If values not found its supposed to be Unknown Title, Unknown Artist, and Unknown Album, but it stays same as last song played that had these properties available. Do you think its because those component stays same for the tracks and video Title and Channel are not present where you are reading from. We could set Title as Title of the video and Artist as channel name that uploaded the video if possible and leave album as "Unknown Album"

**Review by MarshallOfSound — APPROVED** [review]

**Pull request merged**
